# Generated by Django 4.2.7 on 2025-12-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_testcategory_testtype_patienttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttest',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patienttest',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patienttest',
            name='result_value',
            field=models.FloatField(default=0),
        ),
    ]
