# Generated by Django 4.2.7 on 2025-12-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_patienttest_is_published_patienttest_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttest',
            name='test_group',
            field=models.CharField(default='SINGLE', max_length=20),
        ),
    ]
