# Generated by Django 4.2.7 on 2025-12-23 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_patienttest_test_group'),
    ]

    operations = [
    ]
