# Generated by Django 4.2.7 on 2025-12-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20251223_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='patienttest',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='reports.medicalreport'),
        ),
    ]
