# Generated by Django 4.2.7 on 2025-12-24 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0006_patienttest_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(default='MediGen Laboratory', max_length=200)),
                ('lab_address', models.TextField(default='123 Medical Center Drive, Healthcare City')),
                ('lab_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('lab_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Settings',
                'verbose_name_plural': 'Lab Settings',
            },
        ),
    ]
