# Generated by Django 4.2.7 on 2025-12-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_labsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsettings',
            name='lab_logo',
            field=models.ImageField(blank=True, null=True, upload_to='lab_logos/'),
        ),
    ]
