# Generated by Django 4.2.7 on 2026-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_patient_user_alter_patient_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
